import "../styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "replace_project_name",
  description: "Generated by create-convex-next",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
