"use client"

import { useState } from "react"
import { Slot } from "@radix-ui/react-slot"
import { Sun, Moon, ArrowRight } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"

export default function Home() {
  const [dark, setDark] = useState(false)

  function toggleTheme() {
    const nextDark = !dark
    setDark(nextDark)
    if (typeof document !== "undefined") {
      document.documentElement.classList.toggle("dark", nextDark)
    }
  }

  return (
    <main className="flex flex-col items-center justify-center min-h-screen bg-background text-foreground px-4 py-10 gap-10">
      <div className="flex flex-col items-center gap-2">
        <h1 className="text-4xl sm:text-5xl font-bold tracking-tight">
          Welcome to <span className="text-primary">replace_project_name</span>
        </h1>
        <p className="text-muted-foreground text-center max-w-lg">
          Next.js + Tailwind v4 + Shadcn UI — fully loaded template generated by
          your CLI.
        </p>
      </div>

      <Button onClick={toggleTheme} variant="secondary" size="sm">
        {dark ? (
          <span className="flex items-center gap-2">
            <Sun className="size-4" /> Light Mode
          </span>
        ) : (
          <span className="flex items-center gap-2">
            <Moon className="size-4" /> Dark Mode
          </span>
        )}
      </Button>

      <Card className="w-[360px] border border-border/60 shadow-sm bg-card text-card-foreground">
        <CardHeader>
          <CardTitle className="text-lg">Test Shadcn Components</CardTitle>
        </CardHeader>

        <CardContent className="flex flex-col gap-4">
          <Input placeholder="Type something…" />

          <Button className="w-full">Primary Button</Button>
          <Button variant="outline" className="w-full">
            Outline Button
          </Button>

          <Button variant="secondary" size="icon">
            <ArrowRight className="size-4" />
          </Button>

          <Button asChild variant="link">
            <Slot>
              <a href="https://google.com" target="_blank" rel="noreferrer">
                Go to Google (asChild)
              </a>
            </Slot>
          </Button>
        </CardContent>
      </Card>
    </main>
  )
}
